{
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 7. Plotly Dash — Interactive Dashboard\n\nRun this as a `.py` script: `python 7_plotly_dash.py`\nThen open http://127.0.0.1:8050 in your browser."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install if needed:\n",
    "# pip install dash plotly pandas\n",
    "\n",
    "import pandas as pd\n",
    "import dash\n",
    "from dash import dcc, html\n",
    "from dash.dependencies import Input, Output\n",
    "import plotly.express as px\n",
    "\n",
    "# ── Load data ──────────────────────────────────────────────────────────────\n",
    "df = pd.read_csv('../data/dataset_part_2.csv')\n",
    "\n",
    "max_payload = df['PayloadMass'].max()\n",
    "min_payload = df['PayloadMass'].min()\n",
    "\n",
    "# ── App layout ─────────────────────────────────────────────────────────────\n",
    "app = dash.Dash(__name__)\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1('SpaceX Launch Records Dashboard',\n",
    "            style={'textAlign':'center','color':'#503D36','fontSize':24}),\n",
    "\n",
    "    # Dropdown\n",
    "    dcc.Dropdown(\n",
    "        id='site-dropdown',\n",
    "        options=(\n",
    "            [{'label':'All Sites','value':'ALL'}] +\n",
    "            [{'label':s,'value':s} for s in sorted(df['LaunchSite'].unique())]\n",
    "        ),\n",
    "        value='ALL',\n",
    "        placeholder='Select a Launch Site',\n",
    "        searchable=True\n",
    "    ),\n",
    "    html.Br(),\n",
    "\n",
    "    # Pie chart\n",
    "    html.Div(dcc.Graph(id='success-pie-chart')),\n",
    "    html.Br(),\n",
    "\n",
    "    # Payload slider\n",
    "    html.P('Payload range (kg):'),\n",
    "    dcc.RangeSlider(\n",
    "        id='payload-slider',\n",
    "        min=0, max=10000, step=1000,\n",
    "        value=[min_payload, max_payload],\n",
    "        marks={i: str(i) for i in range(0, 10001, 2000)}\n",
    "    ),\n",
    "    html.Br(),\n",
    "\n",
    "    # Scatter chart\n",
    "    html.Div(dcc.Graph(id='success-payload-scatter')),\n",
    "])\n",
    "\n",
    "# ── Callback 1 — Pie chart ─────────────────────────────────────────────────\n",
    "@app.callback(\n",
    "    Output('success-pie-chart','figure'),\n",
    "    Input('site-dropdown','value')\n",
    ")\n",
    "def update_pie(selected_site):\n",
    "    if selected_site == 'ALL':\n",
    "        fig = px.pie(\n",
    "            df, values='Class', names='LaunchSite',\n",
    "            title='Total Success Launches by Site'\n",
    "        )\n",
    "    else:\n",
    "        filtered = df[df['LaunchSite'] == selected_site]\n",
    "        fig = px.pie(\n",
    "            filtered,\n",
    "            names=filtered['Class'].map({1:'Success',0:'Failure'}),\n",
    "            title=f'Success vs Failure — {selected_site}'\n",
    "        )\n",
    "    return fig\n",
    "\n",
    "# ── Callback 2 — Scatter chart ─────────────────────────────────────────────\n",
    "@app.callback(\n",
    "    Output('success-payload-scatter','figure'),\n",
    "    [Input('site-dropdown','value'),\n",
    "     Input('payload-slider','value')]\n",
    ")\n",
    "def update_scatter(selected_site, payload_range):\n",
    "    low, high = payload_range\n",
    "    mask = (df['PayloadMass'] >= low) & (df['PayloadMass'] <= high)\n",
    "    if selected_site != 'ALL':\n",
    "        mask &= (df['LaunchSite'] == selected_site)\n",
    "    filtered = df[mask]\n",
    "    fig = px.scatter(\n",
    "        filtered, x='PayloadMass', y='Class',\n",
    "        color='BoosterVersion',\n",
    "        title='Payload Mass vs Launch Outcome',\n",
    "        labels={'PayloadMass':'Payload Mass (kg)','Class':'Launch Outcome'}\n",
    "    )\n",
    "    return fig\n",
    "\n",
    "# ── Run ────────────────────────────────────────────────────────────────────\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)\n"
   ]
  }
 ]
}